### ISSUE TITLE
[Issue] Caused by: java.lang.UnsupportedOperationException: Merge supports only data classes, UiTheme is not a data class

### ISSUE THREAD

**Issue by eemorenom** [salemove/android-sdk-widgets#965]
Hello Glia team,

From my team we are looking for a way to make the most of the Glia SDK and we have moved to version 2.3.2 of Glia to take advantage of Live Observation.. But we are getting the following error:

MyChatActivity:

`
import android.content.Intent
import android.os.Bundle
import com.glia.androidsdk.Engagement
import com.glia.androidsdk.Glia
import com.glia.androidsdk.screensharing.ScreenSharing
import com.glia.widgets.GliaWidgets
import com.glia.widgets.R
import com.glia.widgets.UiTheme
import com.glia.widgets.call.CallActivity
import com.glia.widgets.chat.ChatActivity
import com.glia.widgets.chat.ChatView
import com.glia.widgets.chat.ChatView.OnNavigateToCallListener
import com.glia.widgets.core.configuration.GliaSdkConfiguration
import com.glia.widgets.view.head.ChatHeadLayout

class MyChatActivity : ChatActivity() {
    private val KEY_WAS_ACTIVITY_FINISHING = "was_activity_finishing"
    private lateinit var chatView: ChatView
    private lateinit var configuration: GliaSdkConfiguration

    private var wasActivityFinishing = true

    private var onEndListener: ChatView.OnEndListener? = ChatView.OnEndListener {
        finish()
    }
    private var onNavigateToCallListener: OnNavigateToCallListener? =
        OnNavigateToCallListener { theme: UiTheme?, mediaType: String? ->
            if(theme != null && mediaType != null){
                navigateToCall(theme, mediaType)
            }
        }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.chat_activity)

        configuration = buildConfiguration()

        chatView = findViewById(R.id.chat_view)
        chatView.apply {
            setConfiguration(configuration)
            setUiTheme(configuration.runTimeTheme)
            setOnEndListener(onEndListener)
            setOnNavigateToCallListener(onNavigateToCallListener)
            startChat(
                configuration.companyName,
                configuration.queueId,
                configuration.contextAssetId,
                true,
                ScreenSharing.Mode.UNBOUNDED,
            )
        }
    }

    override fun onBackPressed() {
        chatView.onBackPressed()
        super.onBackPressed()
    }

    private fun buildConfiguration() = GliaSdkConfiguration.Builder()
        .companyName(companyName)
        .queueId(queueId)
        .runTimeTheme(runTimeUiTheme)
        .contextAssetId(contextUrl)
        .useOverlay(true)
        .build()

    override fun onResume() {
        chatView.onResume()
        Glia.getLiveObservation().resume()
        super.onResume()
    }

    override fun onPause() {
        super.onPause()
        chatView.onPause()
        Glia.getLiveObservation().pause()
    }

    override fun onDestroy() {
        onEndListener = null
        onNavigateToCallListener = null
        chatView.onDestroyView()
        super.onDestroy()
    }

    override fun onSaveInstanceState(outState: Bundle) {
        outState.putBoolean(KEY_WAS_ACTIVITY_FINISHING, isFinishing)
        super.onSaveInstanceState(outState)
    }

    override fun onRestoreInstanceState(savedInstanceState: Bundle) {
        wasActivityFinishing =
            savedInstanceState.getBoolean(KEY_WAS_ACTIVITY_FINISHING, true)
        super.onRestoreInstanceState(savedInstanceState)
    }

    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        GliaWidgets.onActivityResult(requestCode, resultCode, data)
        chatView.onActivityResult(requestCode, resultCode, data)
        super.onActivityResult(requestCode, resultCode, data)
    }

    override fun onRequestPermissionsResult(
        requestCode: Int,
        permissions: Array<String?>,
        grantResults: IntArray
    ) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults)
        GliaWidgets.onRequestPermissionsResult(requestCode, permissions, grantResults)
        chatView.onRequestPermissionsResult(requestCode, grantResults)
    }

    private fun navigateToCall(theme: UiTheme, mediaType: String) {
        val newIntent = Intent(applicationContext, CallActivity::class.java)
        newIntent.putExtra(GliaWidgets.COMPANY_NAME, configuration.companyName)
        newIntent.putExtra(GliaWidgets.QUEUE_ID, configuration.queueId)
        newIntent.putExtra(GliaWidgets.CONTEXT_ASSET_ID, configuration.contextAssetId)
        newIntent.putExtra(GliaWidgets.UI_THEME, theme)
        newIntent.putExtra(GliaWidgets.USE_OVERLAY, true)
        newIntent.putExtra(GliaWidgets.MEDIA_TYPE, convertMediaType(mediaType))
        startActivity(newIntent)
    }

    private fun convertMediaType(mediaType: String) : Engagement.MediaType {
        return when(mediaType) {
            Engagement.MediaType.TEXT.name, "chat" ->  Engagement.MediaType.TEXT
            Engagement.MediaType.AUDIO.name ->  Engagement.MediaType.AUDIO
            Engagement.MediaType.VIDEO.name ->  Engagement.MediaType.VIDEO
            Engagement.MediaType.MESSAGING.name ->  Engagement.MediaType.MESSAGING
            else -> Engagement.MediaType.UNKNOWN
        }
    }

    private val companyName: String?
        get() = intent.getStringExtra(GliaWidgets.COMPANY_NAME)
    private val queueId: String?
        get() = intent.getStringExtra(GliaWidgets.QUEUE_ID)
    private val contextUrl: String?
        get() = intent.getStringExtra(GliaWidgets.CONTEXT_ASSET_ID)
    private val runTimeUiTheme: UiTheme?
        get() = intent.getParcelableExtra(GliaWidgets.UI_THEME)
}
`
My layout:
`
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.glia.widgets.chat.ChatView
        android:id="@+id/chat_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

    <com.glia.widgets.view.head.ChatHeadLayout
        android:id="@+id/chat_head_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
</RelativeLayout>

`

Log when i run my app in Release version and real device:

`
04:11:31 E AndroidRuntime : FATAL EXCEPTION: main
04:11:31 E AndroidRuntime : Process: com.domain.qa, PID: 31842
04:11:31 E AndroidRuntime : java.lang.RuntimeException: Unable to start activity ComponentInfo{com.domain.qa/com.ssb.retail.glia.SSBChatActivity}: android.view.InflateException: Binary XML file line #6 in com.domain.qa:layout/chat_activity: Binary XML file line #6 in com.domain.qa:layout/chat_activity: Error inflating class com.glia.widgets.chat.ChatView
04:11:31 E AndroidRuntime : at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4164)
04:11:31 E AndroidRuntime : at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
04:11:31 E AndroidRuntime : at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
04:11:31 E AndroidRuntime : at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
04:11:31 E AndroidRuntime : at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
04:11:31 E AndroidRuntime : at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
04:11:31 E AndroidRuntime : at android.os.Handler.dispatchMessage(Handler.java:106)
04:11:31 E AndroidRuntime : at android.os.Looper.loopOnce(Looper.java:230)
04:11:31 E AndroidRuntime : at android.os.Looper.loop(Looper.java:319)
04:11:31 E AndroidRuntime : at android.app.ActivityThread.main(ActivityThread.java:8893)
04:11:31 E AndroidRuntime : at java.lang.reflect.Method.invoke(Native Method)
04:11:31 E AndroidRuntime : at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
04:11:31 E AndroidRuntime : at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
04:11:31 E AndroidRuntime : Caused by: android.view.InflateException: Binary XML file line #6 in com.domain.qa:layout/chat_activity: Binary XML file line #6 in com.domain.qa:layout/chat_activity: Error inflating class com.glia.widgets.chat.ChatView
04:11:31 E AndroidRuntime : Caused by: android.view.InflateException: Binary XML file line #6 in com.domain.qa:layout/chat_activity: Error inflating class com.glia.widgets.chat.ChatView
04:11:31 E AndroidRuntime : Caused by: java.lang.reflect.InvocationTargetException
04:11:31 E AndroidRuntime : at java.lang.reflect.Constructor.newInstance0(Native Method)
04:11:31 E AndroidRuntime : at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
04:11:31 E AndroidRuntime : at android.view.LayoutInflater.createView(LayoutInflater.java:882)
04:11:31 E AndroidRuntime : at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1034)
04:11:31 E AndroidRuntime : at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:989)
04:11:31 E AndroidRuntime : at android.view.LayoutInflater.rInflate(LayoutInflater.java:1151)
04:11:31 E AndroidRuntime : at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1112)
04:11:31 E AndroidRuntime : at android.view.LayoutInflater.inflate(LayoutInflater.java:700)
04:11:31 E AndroidRuntime : at android.view.LayoutInflater.inflate(LayoutInflater.java:544)
04:11:31 E AndroidRuntime : at android.view.LayoutInflater.inflate(LayoutInflater.java:491)
04:11:31 E AndroidRuntime : at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(SourceFile:9)
04:11:31 E AndroidRuntime : at androidx.appcompat.app.AppCompatActivity.setContentView(SourceFile:2)
04:11:31 E AndroidRuntime : at com.glia.widgets.chat.ChatActivity.onCreate(SourceFile:3)
04:11:31 E AndroidRuntime : at com.ssb.retail.glia.SSBChatActivity.onCreate(SourceFile:1)
04:11:31 E AndroidRuntime : at android.app.Activity.performCreate(Activity.java:8944)
04:11:31 E AndroidRuntime : at android.app.Activity.performCreate(Activity.java:8913)
04:11:31 E AndroidRuntime : at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
04:11:31 E AndroidRuntime : at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4146)
04:11:31 E AndroidRuntime : at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
04:11:31 E AndroidRuntime : at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
04:11:31 E AndroidRuntime : at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
04:11:31 E AndroidRuntime : at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
04:11:31 E AndroidRuntime : at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
04:11:31 E AndroidRuntime : at android.os.Handler.dispatchMessage(Handler.java:106)
04:11:31 E AndroidRuntime : at android.os.Looper.loopOnce(Looper.java:230)
04:11:31 E AndroidRuntime : at android.os.Looper.loop(Looper.java:319)
04:11:31 E AndroidRuntime : at android.app.ActivityThread.main(ActivityThread.java:8893)
04:11:31 E AndroidRuntime : at java.lang.reflect.Method.invoke(Native Method)
04:11:31 E AndroidRuntime : at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
04:11:31 E AndroidRuntime : at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
04:11:31 E AndroidRuntime : Caused by: java.lang.UnsupportedOperationException: Merge supports only data classes, UiTheme is not a data class
04:11:31 E AndroidRuntime : at com.glia.widgets.helper.CommonExtensionsKt.getFullHybridTheme(SourceFile:4)
04:11:31 E AndroidRuntime : at com.glia.widgets.chat.ChatView.setDefaultTheme(SourceFile:2)
04:11:31 E AndroidRuntime : at com.glia.widgets.chat.ChatView.readTypedArray(SourceFile:3)
04:11:31 E AndroidRuntime : at com.glia.widgets.chat.ChatView.<init>(SourceFile:22)
04:11:31 E AndroidRuntime : at com.glia.widgets.chat.ChatView.<init>(SourceFile:28)
04:11:31 E AndroidRuntime : at com.glia.widgets.chat.ChatView.<init>(SourceFile:27)
04:11:31 E AndroidRuntime : at com.glia.widgets.chat.ChatView.<init>(Unknown Source:11)
04:11:31 E AndroidRuntime : ... 30 more
`

How can I solve it?
It only happens in the Release version

Thanks

**Comment by mikktammeglia** [comment]
Dear @eemorenom,

We don't use GitHub issues for support. Do you have access to Glia Service Desk? Please open a ticket through the service desk and we are happy to help.

Please do add to the ticket though what version of Gradle are you using as the issue you share is connected to Gradle version most probably.
